### ISSUE TITLE
Second game error

### ISSUE THREAD

**Issue by PBJellytime** [PCJones/ultimate-splinterlands-bot#1]
Seem to be getting the below error every second game, first game runs fine

TypeError: Cannot read property 'setUserAgent' of undefined
    at startBotPlayMatch (/home/harg/Desktop/ultimate-splinterlands-bot-master/index.js:118:16)
    at /home/harg/Desktop/ultimate-splinterlands-bot-master/index.js:352:11
    at process._tickCallback (internal/process/next_tick.js:68:7)
Routine error at:  11/09/2021, 03:26:12 TypeError: Cannot read property 'waitForTimeout' of undefined
    at /home/harg/Desktop/ultimate-splinterlands-bot-master/index.js:360:16
    at process._tickCallback (internal/process/next_tick.js:68:7)

edit: only seems to happen if headless is set to false

**Comment by PCJones** [comment]
Can you post your whole .env (except login data)?

**Comment by PBJellytime** [comment]
I might have closed the browser in between games, I'll try to replicate and see if it makes a difference

QUEST_PRIORITY=true
MINUTES_BATTLES_INTERVAL=30
CLAIM_SEASON_REWARD=false
HEADLESS=true
KEEP_BROWSER_OPEN=true
LOGIN_VIA_EMAIL=true
EMAIL=****
ACCUSERNAME=****
PASSWORD=****
