### ISSUE TITLE
Log to File

### ISSUE THREAD

**Issue by instruite** [PCJones/ultimate-splinterlands-bot#15]
Hello, 

Is it possible to log all the messages to File specified through env variable rather than console?
It will be especially useful to run the bot as service/daemon.

Thanks

P.S. it is feature request than bug but can not see the option to set it in tags

**Comment by PCJones** [comment]
I will add this but there are a lot of pull requests regarding the log right now so it might have to wait some days

**Comment by cjearls95** [comment]
Would it be smarter to maybe put this into a SQLite instance so that way it can be easily read/read or allow for reporting in the future. Or maybe JSON/CSV formatting.

**Comment by PCJones** [comment]
Log to file has been added to https://github.com/PCJones/Ultimate-Splinterlands-Bot-V2
If you want JSON/CSV formatting please create a new issue there :)
