### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by zirky** [PCJones/ultimate-splinterlands-bot#2]
Hello
I have this error. Please help.
Routine error at:  12. 9. 2021 19:04:12 TypeError: Cannot read property 'split' of undefined
    at /home/zirky/Stažené/ultimate-splinterlands-bot-master/index.js:366:48
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by PCJones** [comment]
Can you share your .env without password? You can also send it in private via discord or telegram

**Comment by zirky** [comment]
ACCOUNT=....... 
PASSWORD=........ 
LOGIN_VIA_EMAIL=false
HEADLESS=true
KEEP_BROWSER_OPEN=false
QUEST_PRIORITY=true
MINUTES_BATTLES_INTERVAL=30
CLAIM_SEASON_REWARD=false
CLAIM_QUEST_REWARD=true
USE_CLASSIC_BOT_PRIVATE_API=false
API_URL=

**Comment by PCJones** [comment]
ACCOUNT needs to be ACCUSERNAME, see https://github.com/PCJones/ultimate-splinterlands-bot#bot-configuration

**Comment by zirky** [comment]
Sorry. My mistake. So far I have used alfficcadenti / splinterlands-bot where it is set differently .. It seems to work. It can be closed.
Thanks...

**Comment by zirky** [comment]
I thought of adding a function to the code - changing BATTLES_INTERVAL depending on the execution of the daily task. That is - an interval of 10 minutes if the task is not completed. Then back for 30min.

**Comment by PCJones** [comment]
No problem!

I don't think it is necessary if you run the bot for at least 6-8 hours per day every quest should finish anyways. But I'm open to arguments on why this is necessary

**Comment by zirky** [comment]
> No problem!
> 
> I don't think it is necessary if you run the bot for at least 6-8 hours per day every quest should finish anyways. But I'm open to arguments on why this is necessary

It happened to me that the task was not completed with a setting of 20 minutes. But it is possible that this is due to trying bots on a backup account where I have a basic deck of cards.
