### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by PBJellytime** [PCJones/ultimate-splinterlands-bot#3]
Nice update with the battle result thanks.  It could be me again, have the bot working fine on windows using the API, running it on a VM in ubuntu and getting the below API error

API Error { FetchError: invalid json response body at http://splinterlandsapi.pcjones.de:8080/get_team/ reason: Unexpected end of JSON input
    at /home/harg/Desktop/ultimate-splinterlands-bot-master/node_modules/node-fetch/lib/index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at http://splinterlandsapi.pcjones.de:8080/get_team/ reason: Unexpected end of JSON input',
  type: 'invalid-json' }
API failed, using local history with most cards used tactic

.env settings

QUEST_PRIORITY=true
MINUTES_BATTLES_INTERVAL=30
CLAIM_SEASON_REWARD=false
CLAIM_QUEST_REWARD=true
HEADLESS=true
KEEP_BROWSER_OPEN=true
LOGIN_VIA_EMAIL=true
EMAIL=
ACCUSERNAME=
PASSWORD=
USE_API=true
API_URL=http://splinterlandsapi.pcjones.de:8080/
USE_CLASSIC_BOT_PRIVATE_API=false

**Comment by PCJones** [comment]
Do you still have this bug?

**Comment by PBJellytime** [comment]
Nope, I'll close it thanks
